// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BoardState {
    pub identity: __sdk::Identity,
    pub room_code: String,
    pub width: u8,
    pub height: u8,
    pub cells: Vec<u8>,
    pub active_tetromino: u8,
    pub active_dots: Vec<i8>,
    pub active_rotation_index: i8,
    pub active_previous_rotation_index: Option<i8>,
    pub active_previous_offset_kick: Option<u8>,
    pub hold_tetromino: Option<u8>,
    pub preview_pieces: Vec<u8>,
    pub score: u64,
    pub game_state: u8,
    pub rng_state: u64,
    pub rng_inc: u64,
    pub rng_bag: Vec<u8>,
    pub rng_index: u8,
    pub last_action: Option<u8>,
    pub combo: i32,
    pub back_to_back: bool,
    pub pending_garbage: u32,
}

impl __sdk::InModule for BoardState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BoardState`.
///
/// Provides typed access to columns for query building.
pub struct BoardStateCols {
    pub identity: __sdk::__query_builder::Col<BoardState, __sdk::Identity>,
    pub room_code: __sdk::__query_builder::Col<BoardState, String>,
    pub width: __sdk::__query_builder::Col<BoardState, u8>,
    pub height: __sdk::__query_builder::Col<BoardState, u8>,
    pub cells: __sdk::__query_builder::Col<BoardState, Vec<u8>>,
    pub active_tetromino: __sdk::__query_builder::Col<BoardState, u8>,
    pub active_dots: __sdk::__query_builder::Col<BoardState, Vec<i8>>,
    pub active_rotation_index: __sdk::__query_builder::Col<BoardState, i8>,
    pub active_previous_rotation_index: __sdk::__query_builder::Col<BoardState, Option<i8>>,
    pub active_previous_offset_kick: __sdk::__query_builder::Col<BoardState, Option<u8>>,
    pub hold_tetromino: __sdk::__query_builder::Col<BoardState, Option<u8>>,
    pub preview_pieces: __sdk::__query_builder::Col<BoardState, Vec<u8>>,
    pub score: __sdk::__query_builder::Col<BoardState, u64>,
    pub game_state: __sdk::__query_builder::Col<BoardState, u8>,
    pub rng_state: __sdk::__query_builder::Col<BoardState, u64>,
    pub rng_inc: __sdk::__query_builder::Col<BoardState, u64>,
    pub rng_bag: __sdk::__query_builder::Col<BoardState, Vec<u8>>,
    pub rng_index: __sdk::__query_builder::Col<BoardState, u8>,
    pub last_action: __sdk::__query_builder::Col<BoardState, Option<u8>>,
    pub combo: __sdk::__query_builder::Col<BoardState, i32>,
    pub back_to_back: __sdk::__query_builder::Col<BoardState, bool>,
    pub pending_garbage: __sdk::__query_builder::Col<BoardState, u32>,
}

impl __sdk::__query_builder::HasCols for BoardState {
    type Cols = BoardStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BoardStateCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            room_code: __sdk::__query_builder::Col::new(table_name, "room_code"),
            width: __sdk::__query_builder::Col::new(table_name, "width"),
            height: __sdk::__query_builder::Col::new(table_name, "height"),
            cells: __sdk::__query_builder::Col::new(table_name, "cells"),
            active_tetromino: __sdk::__query_builder::Col::new(table_name, "active_tetromino"),
            active_dots: __sdk::__query_builder::Col::new(table_name, "active_dots"),
            active_rotation_index: __sdk::__query_builder::Col::new(
                table_name,
                "active_rotation_index",
            ),
            active_previous_rotation_index: __sdk::__query_builder::Col::new(
                table_name,
                "active_previous_rotation_index",
            ),
            active_previous_offset_kick: __sdk::__query_builder::Col::new(
                table_name,
                "active_previous_offset_kick",
            ),
            hold_tetromino: __sdk::__query_builder::Col::new(table_name, "hold_tetromino"),
            preview_pieces: __sdk::__query_builder::Col::new(table_name, "preview_pieces"),
            score: __sdk::__query_builder::Col::new(table_name, "score"),
            game_state: __sdk::__query_builder::Col::new(table_name, "game_state"),
            rng_state: __sdk::__query_builder::Col::new(table_name, "rng_state"),
            rng_inc: __sdk::__query_builder::Col::new(table_name, "rng_inc"),
            rng_bag: __sdk::__query_builder::Col::new(table_name, "rng_bag"),
            rng_index: __sdk::__query_builder::Col::new(table_name, "rng_index"),
            last_action: __sdk::__query_builder::Col::new(table_name, "last_action"),
            combo: __sdk::__query_builder::Col::new(table_name, "combo"),
            back_to_back: __sdk::__query_builder::Col::new(table_name, "back_to_back"),
            pending_garbage: __sdk::__query_builder::Col::new(table_name, "pending_garbage"),
        }
    }
}

/// Indexed column accessor struct for the table `BoardState`.
///
/// Provides typed access to indexed columns for query building.
pub struct BoardStateIxCols {
    pub identity: __sdk::__query_builder::IxCol<BoardState, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for BoardState {
    type IxCols = BoardStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BoardStateIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}
