// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::board_state_type::BoardState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `board_state`.
///
/// Obtain a handle from the [`BoardStateTableAccess::board_state`] method on [`super::RemoteTables`],
/// like `ctx.db.board_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.board_state().on_insert(...)`.
pub struct BoardStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<BoardState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `board_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BoardStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BoardStateTableHandle`], which mediates access to the table `board_state`.
    fn board_state(&self) -> BoardStateTableHandle<'_>;
}

impl BoardStateTableAccess for super::RemoteTables {
    fn board_state(&self) -> BoardStateTableHandle<'_> {
        BoardStateTableHandle {
            imp: self.imp.get_table::<BoardState>("board_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BoardStateInsertCallbackId(__sdk::CallbackId);
pub struct BoardStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BoardStateTableHandle<'ctx> {
    type Row = BoardState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BoardState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BoardStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BoardStateInsertCallbackId {
        BoardStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BoardStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BoardStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BoardStateDeleteCallbackId {
        BoardStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BoardStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BoardState>("board_state");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}
pub struct BoardStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BoardStateTableHandle<'ctx> {
    type UpdateCallbackId = BoardStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BoardStateUpdateCallbackId {
        BoardStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BoardStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<BoardState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BoardState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `identity` unique index on the table `board_state`,
/// which allows point queries on the field of the same name
/// via the [`BoardStateIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.board_state().identity().find(...)`.
pub struct BoardStateIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<BoardState, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BoardStateTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `board_state`.
    pub fn identity(&self) -> BoardStateIdentityUnique<'ctx> {
        BoardStateIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BoardStateIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<BoardState> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BoardState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait board_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BoardState`.
    fn board_state(&self) -> __sdk::__query_builder::Table<BoardState>;
}

impl board_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn board_state(&self) -> __sdk::__query_builder::Table<BoardState> {
        __sdk::__query_builder::Table::new("board_state")
    }
}
