// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct LeaveRoomArgs {}

impl From<LeaveRoomArgs> for super::Reducer {
    fn from(args: LeaveRoomArgs) -> Self {
        Self::LeaveRoom
    }
}

impl __sdk::InModule for LeaveRoomArgs {
    type Module = super::RemoteModule;
}

pub struct LeaveRoomCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `leave_room`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait leave_room {
    /// Request that the remote module invoke the reducer `leave_room` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_leave_room`] callbacks.
    fn leave_room(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `leave_room`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`LeaveRoomCallbackId`] can be passed to [`Self::remove_on_leave_room`]
    /// to cancel the callback.
    fn on_leave_room(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> LeaveRoomCallbackId;
    /// Cancel a callback previously registered by [`Self::on_leave_room`],
    /// causing it not to run in the future.
    fn remove_on_leave_room(&self, callback: LeaveRoomCallbackId);
}

impl leave_room for super::RemoteReducers {
    fn leave_room(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("leave_room", LeaveRoomArgs {})
    }
    fn on_leave_room(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> LeaveRoomCallbackId {
        LeaveRoomCallbackId(self.imp.on_reducer(
            "leave_room",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::LeaveRoom {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_leave_room(&self, callback: LeaveRoomCallbackId) {
        self.imp.remove_on_reducer("leave_room", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `leave_room`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_leave_room {
    /// Set the call-reducer flags for the reducer `leave_room` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn leave_room(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_leave_room for super::SetReducerFlags {
    fn leave_room(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("leave_room", flags);
    }
}
