// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MatchState {
    pub room_code: String,
    pub tick: u64,
    pub rng_seed: u64,
    pub status: u8,
}

impl __sdk::InModule for MatchState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MatchState`.
///
/// Provides typed access to columns for query building.
pub struct MatchStateCols {
    pub room_code: __sdk::__query_builder::Col<MatchState, String>,
    pub tick: __sdk::__query_builder::Col<MatchState, u64>,
    pub rng_seed: __sdk::__query_builder::Col<MatchState, u64>,
    pub status: __sdk::__query_builder::Col<MatchState, u8>,
}

impl __sdk::__query_builder::HasCols for MatchState {
    type Cols = MatchStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MatchStateCols {
            room_code: __sdk::__query_builder::Col::new(table_name, "room_code"),
            tick: __sdk::__query_builder::Col::new(table_name, "tick"),
            rng_seed: __sdk::__query_builder::Col::new(table_name, "rng_seed"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
        }
    }
}

/// Indexed column accessor struct for the table `MatchState`.
///
/// Provides typed access to indexed columns for query building.
pub struct MatchStateIxCols {
    pub room_code: __sdk::__query_builder::IxCol<MatchState, String>,
}

impl __sdk::__query_builder::HasIxCols for MatchState {
    type IxCols = MatchStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MatchStateIxCols {
            room_code: __sdk::__query_builder::IxCol::new(table_name, "room_code"),
        }
    }
}
