// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::match_state_type::MatchState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `match_state`.
///
/// Obtain a handle from the [`MatchStateTableAccess::match_state`] method on [`super::RemoteTables`],
/// like `ctx.db.match_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.match_state().on_insert(...)`.
pub struct MatchStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<MatchState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `match_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MatchStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MatchStateTableHandle`], which mediates access to the table `match_state`.
    fn match_state(&self) -> MatchStateTableHandle<'_>;
}

impl MatchStateTableAccess for super::RemoteTables {
    fn match_state(&self) -> MatchStateTableHandle<'_> {
        MatchStateTableHandle {
            imp: self.imp.get_table::<MatchState>("match_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MatchStateInsertCallbackId(__sdk::CallbackId);
pub struct MatchStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MatchStateTableHandle<'ctx> {
    type Row = MatchState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MatchStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchStateInsertCallbackId {
        MatchStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MatchStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MatchStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchStateDeleteCallbackId {
        MatchStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MatchStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MatchState>("match_state");
    _table.add_unique_constraint::<String>("room_code", |row| &row.room_code);
}
pub struct MatchStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MatchStateTableHandle<'ctx> {
    type UpdateCallbackId = MatchStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MatchStateUpdateCallbackId {
        MatchStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MatchStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<MatchState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MatchState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `room_code` unique index on the table `match_state`,
/// which allows point queries on the field of the same name
/// via the [`MatchStateRoomCodeUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.match_state().room_code().find(...)`.
pub struct MatchStateRoomCodeUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MatchState, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MatchStateTableHandle<'ctx> {
    /// Get a handle on the `room_code` unique index on the table `match_state`.
    pub fn room_code(&self) -> MatchStateRoomCodeUnique<'ctx> {
        MatchStateRoomCodeUnique {
            imp: self.imp.get_unique_constraint::<String>("room_code"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MatchStateRoomCodeUnique<'ctx> {
    /// Find the subscribed row whose `room_code` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<MatchState> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MatchState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait match_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MatchState`.
    fn match_state(&self) -> __sdk::__query_builder::Table<MatchState>;
}

impl match_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn match_state(&self) -> __sdk::__query_builder::Table<MatchState> {
        __sdk::__query_builder::Table::new("match_state")
    }
}
