// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PendingInput {
    pub identity: __sdk::Identity,
    pub room_code: String,
    pub tick: u64,
    pub input_bits: u16,
}

impl __sdk::InModule for PendingInput {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PendingInput`.
///
/// Provides typed access to columns for query building.
pub struct PendingInputCols {
    pub identity: __sdk::__query_builder::Col<PendingInput, __sdk::Identity>,
    pub room_code: __sdk::__query_builder::Col<PendingInput, String>,
    pub tick: __sdk::__query_builder::Col<PendingInput, u64>,
    pub input_bits: __sdk::__query_builder::Col<PendingInput, u16>,
}

impl __sdk::__query_builder::HasCols for PendingInput {
    type Cols = PendingInputCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PendingInputCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            room_code: __sdk::__query_builder::Col::new(table_name, "room_code"),
            tick: __sdk::__query_builder::Col::new(table_name, "tick"),
            input_bits: __sdk::__query_builder::Col::new(table_name, "input_bits"),
        }
    }
}

/// Indexed column accessor struct for the table `PendingInput`.
///
/// Provides typed access to indexed columns for query building.
pub struct PendingInputIxCols {
    pub identity: __sdk::__query_builder::IxCol<PendingInput, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for PendingInput {
    type IxCols = PendingInputIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PendingInputIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}
