// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::pending_input_type::PendingInput;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `pending_input`.
///
/// Obtain a handle from the [`PendingInputTableAccess::pending_input`] method on [`super::RemoteTables`],
/// like `ctx.db.pending_input()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pending_input().on_insert(...)`.
pub struct PendingInputTableHandle<'ctx> {
    imp: __sdk::TableHandle<PendingInput>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `pending_input`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PendingInputTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PendingInputTableHandle`], which mediates access to the table `pending_input`.
    fn pending_input(&self) -> PendingInputTableHandle<'_>;
}

impl PendingInputTableAccess for super::RemoteTables {
    fn pending_input(&self) -> PendingInputTableHandle<'_> {
        PendingInputTableHandle {
            imp: self.imp.get_table::<PendingInput>("pending_input"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PendingInputInsertCallbackId(__sdk::CallbackId);
pub struct PendingInputDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PendingInputTableHandle<'ctx> {
    type Row = PendingInput;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PendingInput> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PendingInputInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PendingInputInsertCallbackId {
        PendingInputInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PendingInputInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PendingInputDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PendingInputDeleteCallbackId {
        PendingInputDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PendingInputDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PendingInput>("pending_input");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}
pub struct PendingInputUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PendingInputTableHandle<'ctx> {
    type UpdateCallbackId = PendingInputUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PendingInputUpdateCallbackId {
        PendingInputUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PendingInputUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PendingInput>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PendingInput>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `identity` unique index on the table `pending_input`,
/// which allows point queries on the field of the same name
/// via the [`PendingInputIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pending_input().identity().find(...)`.
pub struct PendingInputIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PendingInput, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PendingInputTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `pending_input`.
    pub fn identity(&self) -> PendingInputIdentityUnique<'ctx> {
        PendingInputIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PendingInputIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<PendingInput> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PendingInput`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait pending_inputQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PendingInput`.
    fn pending_input(&self) -> __sdk::__query_builder::Table<PendingInput>;
}

impl pending_inputQueryTableAccess for __sdk::QueryTableAccessor {
    fn pending_input(&self) -> __sdk::__query_builder::Table<PendingInput> {
        __sdk::__query_builder::Table::new("pending_input")
    }
}
