// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Player {
    pub identity: __sdk::Identity,
    pub room_code: String,
    pub seat: u8,
    pub is_ready: bool,
}

impl __sdk::InModule for Player {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Player`.
///
/// Provides typed access to columns for query building.
pub struct PlayerCols {
    pub identity: __sdk::__query_builder::Col<Player, __sdk::Identity>,
    pub room_code: __sdk::__query_builder::Col<Player, String>,
    pub seat: __sdk::__query_builder::Col<Player, u8>,
    pub is_ready: __sdk::__query_builder::Col<Player, bool>,
}

impl __sdk::__query_builder::HasCols for Player {
    type Cols = PlayerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            room_code: __sdk::__query_builder::Col::new(table_name, "room_code"),
            seat: __sdk::__query_builder::Col::new(table_name, "seat"),
            is_ready: __sdk::__query_builder::Col::new(table_name, "is_ready"),
        }
    }
}

/// Indexed column accessor struct for the table `Player`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerIxCols {
    pub identity: __sdk::__query_builder::IxCol<Player, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Player {
    type IxCols = PlayerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}
