// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Room {
    pub code: String,
    pub owner: __sdk::Identity,
    pub max_players: u8,
    pub status: u8,
}

impl __sdk::InModule for Room {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Room`.
///
/// Provides typed access to columns for query building.
pub struct RoomCols {
    pub code: __sdk::__query_builder::Col<Room, String>,
    pub owner: __sdk::__query_builder::Col<Room, __sdk::Identity>,
    pub max_players: __sdk::__query_builder::Col<Room, u8>,
    pub status: __sdk::__query_builder::Col<Room, u8>,
}

impl __sdk::__query_builder::HasCols for Room {
    type Cols = RoomCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RoomCols {
            code: __sdk::__query_builder::Col::new(table_name, "code"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            max_players: __sdk::__query_builder::Col::new(table_name, "max_players"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
        }
    }
}

/// Indexed column accessor struct for the table `Room`.
///
/// Provides typed access to indexed columns for query building.
pub struct RoomIxCols {
    pub code: __sdk::__query_builder::IxCol<Room, String>,
}

impl __sdk::__query_builder::HasIxCols for Room {
    type IxCols = RoomIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RoomIxCols {
            code: __sdk::__query_builder::IxCol::new(table_name, "code"),
        }
    }
}
