// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StartMatchArgs {
    pub code: String,
}

impl From<StartMatchArgs> for super::Reducer {
    fn from(args: StartMatchArgs) -> Self {
        Self::StartMatch { code: args.code }
    }
}

impl __sdk::InModule for StartMatchArgs {
    type Module = super::RemoteModule;
}

pub struct StartMatchCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `start_match`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait start_match {
    /// Request that the remote module invoke the reducer `start_match` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_start_match`] callbacks.
    fn start_match(&self, code: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `start_match`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`StartMatchCallbackId`] can be passed to [`Self::remove_on_start_match`]
    /// to cancel the callback.
    fn on_start_match(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> StartMatchCallbackId;
    /// Cancel a callback previously registered by [`Self::on_start_match`],
    /// causing it not to run in the future.
    fn remove_on_start_match(&self, callback: StartMatchCallbackId);
}

impl start_match for super::RemoteReducers {
    fn start_match(&self, code: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("start_match", StartMatchArgs { code })
    }
    fn on_start_match(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> StartMatchCallbackId {
        StartMatchCallbackId(self.imp.on_reducer(
            "start_match",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::StartMatch { code },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, code)
            }),
        ))
    }
    fn remove_on_start_match(&self, callback: StartMatchCallbackId) {
        self.imp.remove_on_reducer("start_match", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `start_match`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_start_match {
    /// Set the call-reducer flags for the reducer `start_match` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn start_match(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_start_match for super::SetReducerFlags {
    fn start_match(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("start_match", flags);
    }
}
