// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SubmitInputArgs {
    pub room_code: String,
    pub input_bits: u16,
    pub client_tick: u64,
}

impl From<SubmitInputArgs> for super::Reducer {
    fn from(args: SubmitInputArgs) -> Self {
        Self::SubmitInput {
            room_code: args.room_code,
            input_bits: args.input_bits,
            client_tick: args.client_tick,
        }
    }
}

impl __sdk::InModule for SubmitInputArgs {
    type Module = super::RemoteModule;
}

pub struct SubmitInputCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `submit_input`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait submit_input {
    /// Request that the remote module invoke the reducer `submit_input` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_submit_input`] callbacks.
    fn submit_input(
        &self,
        room_code: String,
        input_bits: u16,
        client_tick: u64,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `submit_input`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SubmitInputCallbackId`] can be passed to [`Self::remove_on_submit_input`]
    /// to cancel the callback.
    fn on_submit_input(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &u16, &u64) + Send + 'static,
    ) -> SubmitInputCallbackId;
    /// Cancel a callback previously registered by [`Self::on_submit_input`],
    /// causing it not to run in the future.
    fn remove_on_submit_input(&self, callback: SubmitInputCallbackId);
}

impl submit_input for super::RemoteReducers {
    fn submit_input(
        &self,
        room_code: String,
        input_bits: u16,
        client_tick: u64,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "submit_input",
            SubmitInputArgs {
                room_code,
                input_bits,
                client_tick,
            },
        )
    }
    fn on_submit_input(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &u16, &u64) + Send + 'static,
    ) -> SubmitInputCallbackId {
        SubmitInputCallbackId(self.imp.on_reducer(
            "submit_input",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::SubmitInput {
                                    room_code,
                                    input_bits,
                                    client_tick,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, room_code, input_bits, client_tick)
            }),
        ))
    }
    fn remove_on_submit_input(&self, callback: SubmitInputCallbackId) {
        self.imp.remove_on_reducer("submit_input", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `submit_input`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_submit_input {
    /// Set the call-reducer flags for the reducer `submit_input` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn submit_input(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_submit_input for super::SetReducerFlags {
    fn submit_input(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("submit_input", flags);
    }
}
