// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TickArgs {
    pub room_code: String,
}

impl From<TickArgs> for super::Reducer {
    fn from(args: TickArgs) -> Self {
        Self::Tick {
            room_code: args.room_code,
        }
    }
}

impl __sdk::InModule for TickArgs {
    type Module = super::RemoteModule;
}

pub struct TickCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `tick`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait tick {
    /// Request that the remote module invoke the reducer `tick` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_tick`] callbacks.
    fn tick(&self, room_code: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `tick`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`TickCallbackId`] can be passed to [`Self::remove_on_tick`]
    /// to cancel the callback.
    fn on_tick(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> TickCallbackId;
    /// Cancel a callback previously registered by [`Self::on_tick`],
    /// causing it not to run in the future.
    fn remove_on_tick(&self, callback: TickCallbackId);
}

impl tick for super::RemoteReducers {
    fn tick(&self, room_code: String) -> __sdk::Result<()> {
        self.imp.call_reducer("tick", TickArgs { room_code })
    }
    fn on_tick(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> TickCallbackId {
        TickCallbackId(self.imp.on_reducer(
            "tick",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::Tick { room_code },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, room_code)
            }),
        ))
    }
    fn remove_on_tick(&self, callback: TickCallbackId) {
        self.imp.remove_on_reducer("tick", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `tick`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_tick {
    /// Set the call-reducer flags for the reducer `tick` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn tick(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_tick for super::SetReducerFlags {
    fn tick(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("tick", flags);
    }
}
